//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPM.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int Id { get; set; }
        public string Customer_Number { get; set; }
        public string Customer_First_Name { get; set; }
        public string Customer_Last_Name { get; set; }
        public string Customer_Phone_Number { get; set; }
    }
}
